--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/SitWands
build-by-default: true
branches:
- main
projects:
  SitWands:
    path: ""
    icon: "EB49A503-A086-4E28-B756-79268CA008E4 (1).jpg"
...
