name: RedstonePVP
version: "1.0.0"
author: usy4
api: "4.0.0"

main: usy4\Main
src-namespace-prefix: usy4

permissions:
  redstonepvp.command.redstonepvp:
    default: op
    description: "permission for use redstone command"

  redstonepvp.command.redstonepvpmanage:
    default: op

  redstonepvp.command.redstonepvpmanage.itemframeshop:
    default: op